apiVersion: v1
kind: Service
metadata:
  name: pf-llm-testing-service
  namespace: pf-llm-testing
spec:
  selector:
    app: pf-llm-testing-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
