FROM nginx:alpine

WORKDIR /usr/src/app

RUN apk add --no-cache nodejs npm

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY src ./src
COPY data ./data

EXPOSE 3000

CMD ["npm", "start"]
